language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-27
  - ANDROID_API_LEVEL=27
  - ANDROID_EMULATOR_API=27
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - ANDROID_ABI=google_apis/armeabi-v7a
  - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

notifications:
  slack:
    secure: O/5cHdrh/1t+DXx7T9tC4QK/e+RKx5KeGiPHuK1v4k7YSg8eqPJzlXQKqBHlr2oN2tlcGLHQ2TVKrLfdQHdcqnLDVanqcCisdf3kW8+LbW3evpop5KkRGQ6LPxPNRqQqu5v9X/4lETBpblaf3Lf/Nce2l09koEpKhrW2fuEwrgYGn26XF21G9aE42VwaEOfBrOHItcERWlhglHDoZv44napVTtKAUq9ge0wzsBs2aUvqEQHawCKGBzjeQ56d1dHs/d/OjrCmie3KHtPSGb+3ZCYXJa2RvO9WumCPEpw6ZcHPmtgafdXa0hl509YyTG0GUbrJPdz5F+nCVtlcMH7CTVLRokOUc8vYJR36KdsPEOeHCz4qto5JkUsSl9Hu6O4w2K25J/5NDxvDPw4MPwCbBDMj+haOnD63jKrqAcmIxTob8zx8kPD1w72ai3Ps3yRHkA9532plWPYTPtNFVifX5xprMgpRhJBC1PJOESb1YBni9u/nE2lOUQolVbw9IGJLo/aLahaEVIDthaoSyc1f2eYyHbK8UA1QW1ce2x677ECgBaCZvDii6Mb4BzBP+vRsn8slcn0nCs55arEh3TYy1+HggugTSLg/P++k3n7vA+cWoxsYeQvEBTa6sR1yil25DHZ8hscdK4hlABQds4T42YPgE2fjnmLIYnwVdV8kIeU=

android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-google_apis-google-$ANDROID_API_LEVEL

before_install:
  - chmod +x gradlew
  - cd $TRAVIS_BUILD_DIR/
  - pip install --user codecov

before_script:
  - echo no | android create avd --force -n test -t android-27 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport
  - ./gradlew check

after_success:
  - ./gradlew jacocoFullReport
  - codecov
  - bash <(curl -s https://codecov.io/bash)


